#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SCRIPT_PATH}/.shared

BLITE=${SCRIPT_PATH}/../bin/blite

if [ -z "$(${BLITE} status | grep running)" ]; then
  echo "There doesn't seem to be a blite director running. Run make bosh-lite before running this command."
  echo "Alternatively run the binary yourself with a custom configuration. This local-dev setup is meant to be used with bosh-lite."
  exit 1
fi

DIRECTOR_IP=$(${BLITE} networking | grep BLITE_DIRECTOR_IP | awk '{print $2}')

VAULT_CFCS_UAA_ADDRESS=https://${DIRECTOR_IP}:8443 ./bin/vault-cfcs -config local-dev/config/local-dev.json