#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SCRIPT_PATH}/.shared

BLITE=${SCRIPT_PATH}/../bin/blite

eval $(${BLITE} env-eval)

bosh -d redis deploy ${SCRIPT_PATH}/../local-dev/test-manifests/redis.yml