#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SCRIPT_PATH}/.shared

BLITE=${SCRIPT_PATH}/../../bin/blite

export BLITE_OPS_FILE_GLOB=${SCRIPT_PATH}/../operators/*-local-dev-*.yml
export BLITE_VARS_FILE_GLOB=${LOCAL_DEV_VARS_PATH}

${BLITE} create

${BLITE} interpolate /instance_groups/0/properties/director/config_server/uaa/ca_cert > ${DIRECTOR_CA_CERT_PATH}
eval $(${BLITE} env-eval)

${BLITE} cloud-config
bosh -n upload-stemcell https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3469.1-warden-boshlite-ubuntu-trusty-go_agent.tgz --sha1 6f1244d02e2f554fa57763f07a2707da373b18aa
