#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SCRIPT_PATH}/.shared

BLITE=${SCRIPT_PATH}/../../bin/blite

if [[ -z "$(${BLITE} status | grep running)" ]]; then
  echo "There doesn't seem to be a blite director running. Run make bosh-lite before running this command."
  echo "Alternatively run the binary yourself with a custom configuration. This local-dev setup is meant to be used with bosh-lite."
  exit 1
fi

VAULT_UP_CHECK=$(VAULT_ADDR=http://127.0.0.1:8200 VAULT_SKIP_VERIFY=1 vault status 2>&1| grep "Error checking")
if [[ ! -z "${VAULT_UP_CHECK}" ]]; then
  echo "Looks like your local Vault server isn't running! Have you run make vault?"
  exit 1
fi

VAULT_SEALED_CHECK=$(VAULT_ADDR=http://127.0.0.1:8200 VAULT_SKIP_VERIFY=1 vault status | grep Sealed | grep false)
if [[ -z "${VAULT_SEALED_CHECK}" ]]; then
  echo "Looks like your local Vault server is sealed! Have you run make unseal?"
  exit 1
fi

DIRECTOR_IP=$(${BLITE} networking | grep BLITE_DIRECTOR_IP | awk '{print $2}')
PERIODIC_TOKEN=$(VAULT_ADDR=http://127.0.0.1:8200 VAULT_SKIP_VERIFY=1 VAULT_TOKEN=s.48t1wu9P4mLBgzvA1LOMJ7AV vault token create -format=json -period=168h -policy=config-server -display-name=bosh-vault-config-server | jq -r .auth.client_token)

BV_VAULT_TOKEN=${PERIODIC_TOKEN} BV_UAA_ADDRESS=https://${DIRECTOR_IP}:8443 ./bin/bosh-vault -config local-dev/config/local-dev.yml
