#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${SCRIPT_PATH}/.shared

BLITE=${SCRIPT_PATH}/../../bin/blite

eval $(${BLITE} env-eval)

if [ -z "$(${BLITE} status | grep running)" ]; then
  echo "There doesn't seem to be a blite director running. Run make run or make bosh-lite before running this command."
  exit 1
fi

bosh -d redis deploy ${MANIFESTS_PATH}/redis.yml